In [95]:
import tensorflow as tf
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.reset_default_graph()


In [96]:
a = tf.constant(2)

In [97]:
b = tf.constant(3)
x = tf.add(a,b)
writer = tf.summary.FileWriter("./graphs", tf.get_default_graph())


In [98]:
with tf.Session() as sess:
    print(sess.run(x))
    writer = tf.summary.FileWriter("./graphs", sess.graph)
writer.close()  
    

5


In [99]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

In [100]:
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

In [101]:
with tf.Session() as sess:
    print(sess.run(x))

5


In [102]:
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')

In [103]:
x = tf.multiply(a, b, name='mul')

In [104]:
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [105]:
zeros = tf.zeros([2,3], tf.int32)

In [106]:
with tf.Session() as sess:
    print(sess.run(zeros))

[[0 0 0]
 [0 0 0]]


In [107]:
like = tf.zeros_like(zeros)

In [108]:
with tf.Session() as sess:
    print(sess.run(like))

[[0 0 0]
 [0 0 0]]


In [109]:
ones = tf.ones_like(zeros, dtype=None, name=None, optimize= True)


In [110]:
with tf.Session() as sess:
    print(sess.run(ones))
    

[[1 1 1]
 [1 1 1]]


In [111]:
fill = tf.fill([2,3], 8)

In [112]:
with tf.Session() as sess:
    print(sess.run(fill))

[[8 8 8]
 [8 8 8]]


In [113]:
# tf.lin_space(start, stop, num, name=None) 
lin_space = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(lin_space))

[10. 11. 12. 13.]


In [114]:
# tf.range(start, limit=None, delta=1, dtype=None, name='range')
range_3 = tf.range(3, 18,3)
range_ = tf.range(5)
with tf.Session() as sess:
    print(sess.run(range_3))
    print(sess.run(range_))

[ 3  6  9 12 15]
[0 1 2 3 4]


In [115]:
tf.reset_default_graph()

a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')
with tf.Session() as sess:
    print('sess.run(tf.div(b,a))', sess.run(tf.div(b,a)))
    print('sess.run(tf.divide(b,a))', sess.run(tf.divide(b,a)))    
    print('sess.run(tf.truediv(b,a))', sess.run(tf.truediv(b,a)))    
    print('sess.run(tf.floordiv(b,a))', sess.run(tf.floordiv(b,a)))    
    # print(sess.run(tf.realdiv(b,a)))  # only work for real value  
    print('sess.run(tf.truncatediv(b,a))', sess.run(tf.truncatediv(b,a)))    
    print('sess.run(tf.floor_div(b,a))', sess.run(tf.floor_div(b,a)))    

sess.run(tf.div(b,a)) [[0 0]
 [1 1]]
sess.run(tf.divide(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.truediv(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.floordiv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.truncatediv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.floor_div(b,a)) [[0 0]
 [1 1]]


In [118]:
t_O = 19
zeros = tf.zeros_like(t_O)
ones = tf.ones_like(t_O)
with tf.Session() as sess:
    print(sess.run(zeros))
    print(sess.run(ones))    

0
1


In [126]:
t_1 = [b"apple", b"peach", b"grape"]
zeros_t_1 = tf.zeros_like(t_1)
with tf.Session() as sess:
    print(sess.run(zeros_t_1))

[b'' b'' b'']
