In [95]:
import tensorflow as tf
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.reset_default_graph()


In [96]:
a = tf.constant(2)

In [97]:
b = tf.constant(3)
x = tf.add(a,b)
writer = tf.summary.FileWriter("./graphs", tf.get_default_graph())


In [98]:
with tf.Session() as sess:
    print(sess.run(x))
    writer = tf.summary.FileWriter("./graphs", sess.graph)
writer.close()  
    

5


In [99]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

In [100]:
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

In [101]:
with tf.Session() as sess:
    print(sess.run(x))

5


In [102]:
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')

In [103]:
x = tf.multiply(a, b, name='mul')

In [104]:
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [105]:
zeros = tf.zeros([2,3], tf.int32)

In [106]:
with tf.Session() as sess:
    print(sess.run(zeros))

[[0 0 0]
 [0 0 0]]


In [107]:
like = tf.zeros_like(zeros)

In [108]:
with tf.Session() as sess:
    print(sess.run(like))

[[0 0 0]
 [0 0 0]]


In [109]:
ones = tf.ones_like(zeros, dtype=None, name=None, optimize= True)


In [110]:
with tf.Session() as sess:
    print(sess.run(ones))
    

[[1 1 1]
 [1 1 1]]


In [111]:
fill = tf.fill([2,3], 8)

In [112]:
with tf.Session() as sess:
    print(sess.run(fill))

[[8 8 8]
 [8 8 8]]


In [113]:
# tf.lin_space(start, stop, num, name=None) 
lin_space = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(lin_space))

[10. 11. 12. 13.]


In [114]:
# tf.range(start, limit=None, delta=1, dtype=None, name='range')
range_3 = tf.range(3, 18,3)
range_ = tf.range(5)
with tf.Session() as sess:
    print(sess.run(range_3))
    print(sess.run(range_))

[ 3  6  9 12 15]
[0 1 2 3 4]


In [137]:
tf.reset_default_graph()

a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')
with tf.Session() as sess:
    print('sess.run(tf.div(b,a))', sess.run(tf.div(b,a)))
    print('sess.run(tf.divide(b,a))', sess.run(tf.divide(b,a)))    
    print('sess.run(tf.truediv(b,a))', sess.run(tf.truediv(b,a)))    
    print('sess.run(tf.floordiv(b,a))', sess.run(tf.floordiv(b,a)))    
    # print(sess.run(tf.realdiv(b,a)))  # only work for real value  
    print('sess.run(tf.truncatediv(b,a))', sess.run(tf.truncatediv(b,a)))    
    print('sess.run(tf.floor_div(b,a))', sess.run(tf.floor_div(b,a)))    

sess.run(tf.div(b,a)) [[0 0]
 [1 1]]
sess.run(tf.divide(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.truediv(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.floordiv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.truncatediv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.floor_div(b,a)) [[0 0]
 [1 1]]


In [138]:
t_O = 19
zeros = tf.zeros_like(t_O)
ones = tf.ones_like(t_O)
with tf.Session() as sess:
    print(sess.run(zeros))
    print(sess.run(ones))    

0
1


In [145]:
tf.reset_default_graph()
t_1 = [b"apple", b"peach", b"grape"]
zeros_t_1 = tf.zeros_like(t_1)
# ones_t_1 = tf.ones_like(t_1)
t_2 = [[True, False,False],
        [False, False, True],
        [False, True, False]]
zeros_t_2 = tf.zeros_like(t_2)
ones_t_2 = tf.ones_like(t_2)

with tf.Session() as sess:
    print(sess.run(zeros_t_1))
    # print(sess.run(ones_t_1)) #Expected string, got 1 of type 'int' instead.
    print(sess.run(zeros_t_2))
    print(sess.run(ones_t_2))


[b'' b'' b'']
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [147]:
import numpy as np
tf.int32 == np.int32

True

In [154]:
tf.ones([2,2], np.float32)
sess = tf.Session()
a = tf.zeros([2,3],np.int32)
print(type(a))
a = sess.run(a)
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [156]:
my_const = tf.constant([1.0, 2.0], name='my_const')
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "zeros_like/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: 3
          }
        }
        string_val: "apple"
        string_val: "peach"
        string_val: "grape"
      }
    }
  }
}
node {
  name: "zeros_like"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: 3
          }
        }
        string_val: ""
      }
    }
  }
}
node {
  name: "zeros_like_1/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 3
  

In [162]:
s = tf.Variable(2, name='scalar')
m = tf.Variable([[0,1], [2,3]], name= 'matrix')
w = tf.Variable(tf.zeros([784, 10]))

In [164]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[0,1],[2,3]]))
w = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

In [172]:
with tf.Session() as sess:
    print('a')
    # sess.run(w)# FailedPreconditionError: Attempting to use uninitialized value Variable

# the easiest way is initializing all variables at once
#Initialize a single variable
w = tf.Variable(tf.zeros([784, 10]))
with tf.Session() as sess:
    # sess.run(tf.variables_initializer([a,b]))
    sess.run(w.initializer)


a


In [174]:
#Eval() a variable
w =  tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w)
    print(w.eval())

<tf.Variable 'Variable_6:0' shape=(700, 10) dtype=float32_ref>
[[ 1.2863097  -0.7669186  -0.70167714 ... -0.12248857  1.2840098
   1.2163002 ]
 [ 1.6627645   1.1567808  -1.209143   ... -0.53450644 -1.0928831
  -0.06442116]
 [ 1.0743396   0.42647526 -0.6912071  ... -0.1038226  -0.09148867
   0.43755782]
 ...
 [ 1.626101    0.12967005  0.7257158  ... -0.7124666   0.28813192
  -0.43788666]
 [ 1.8688033  -1.3591282  -1.1510141  ...  0.0498857   1.2325557
  -1.3918943 ]
 [-0.9599584  -0.62643147  0.69786936 ...  1.2385787   1.6092448
   0.8995137 ]]


In [175]:
w = tf.Variable(10)
w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

10
