In [257]:
import tensorflow as tf
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.reset_default_graph()


In [258]:
a = tf.constant(2)

In [259]:
b = tf.constant(3)
x = tf.add(a,b)
writer = tf.summary.FileWriter("./graphs", tf.get_default_graph())


In [260]:
with tf.Session() as sess:
    print(sess.run(x))
    writer = tf.summary.FileWriter("./graphs", sess.graph)
writer.close()  
    

5


In [181]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

In [182]:
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

In [183]:
with tf.Session() as sess:
    print(sess.run(x))

5


In [184]:
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')

In [185]:
x = tf.multiply(a, b, name='mul')

In [186]:
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


In [187]:
zeros = tf.zeros([2,3], tf.int32)

In [188]:
with tf.Session() as sess:
    print(sess.run(zeros))

[[0 0 0]
 [0 0 0]]


In [189]:
like = tf.zeros_like(zeros)

In [190]:
with tf.Session() as sess:
    print(sess.run(like))

[[0 0 0]
 [0 0 0]]


In [191]:
ones = tf.ones_like(zeros, dtype=None, name=None, optimize= True)


In [192]:
with tf.Session() as sess:
    print(sess.run(ones))
    

[[1 1 1]
 [1 1 1]]


In [193]:
fill = tf.fill([2,3], 8)

In [194]:
with tf.Session() as sess:
    print(sess.run(fill))

[[8 8 8]
 [8 8 8]]


In [195]:
# tf.lin_space(start, stop, num, name=None) 
lin_space = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(lin_space))

[10. 11. 12. 13.]


In [196]:
# tf.range(start, limit=None, delta=1, dtype=None, name='range')
range_3 = tf.range(3, 18,3)
range_ = tf.range(5)
with tf.Session() as sess:
    print(sess.run(range_3))
    print(sess.run(range_))

[ 3  6  9 12 15]
[0 1 2 3 4]


In [197]:
tf.reset_default_graph()

a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')
with tf.Session() as sess:
    print('sess.run(tf.div(b,a))', sess.run(tf.div(b,a)))
    print('sess.run(tf.divide(b,a))', sess.run(tf.divide(b,a)))    
    print('sess.run(tf.truediv(b,a))', sess.run(tf.truediv(b,a)))    
    print('sess.run(tf.floordiv(b,a))', sess.run(tf.floordiv(b,a)))    
    # print(sess.run(tf.realdiv(b,a)))  # only work for real value  
    print('sess.run(tf.truncatediv(b,a))', sess.run(tf.truncatediv(b,a)))    
    print('sess.run(tf.floor_div(b,a))', sess.run(tf.floor_div(b,a)))    

sess.run(tf.div(b,a)) [[0 0]
 [1 1]]
sess.run(tf.divide(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.truediv(b,a)) [[0.  0.5]
 [1.  1.5]]
sess.run(tf.floordiv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.truncatediv(b,a)) [[0 0]
 [1 1]]
sess.run(tf.floor_div(b,a)) [[0 0]
 [1 1]]


In [198]:
t_O = 19
zeros = tf.zeros_like(t_O)
ones = tf.ones_like(t_O)
with tf.Session() as sess:
    print(sess.run(zeros))
    print(sess.run(ones))    

0
1


In [199]:
tf.reset_default_graph()
t_1 = [b"apple", b"peach", b"grape"]
zeros_t_1 = tf.zeros_like(t_1)
# ones_t_1 = tf.ones_like(t_1)
t_2 = [[True, False,False],
        [False, False, True],
        [False, True, False]]
zeros_t_2 = tf.zeros_like(t_2)
ones_t_2 = tf.ones_like(t_2)

with tf.Session() as sess:
    print(sess.run(zeros_t_1))
    # print(sess.run(ones_t_1)) #Expected string, got 1 of type 'int' instead.
    print(sess.run(zeros_t_2))
    print(sess.run(ones_t_2))


[b'' b'' b'']
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [200]:
import numpy as np
tf.int32 == np.int32

True

In [201]:
tf.ones([2,2], np.float32)
sess = tf.Session()
a = tf.zeros([2,3],np.int32)
print(type(a))
a = sess.run(a)
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [202]:
my_const = tf.constant([1.0, 2.0], name='my_const')
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "zeros_like/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: 3
          }
        }
        string_val: "apple"
        string_val: "peach"
        string_val: "grape"
      }
    }
  }
}
node {
  name: "zeros_like"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_STRING
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_STRING
        tensor_shape {
          dim {
            size: 3
          }
        }
        string_val: ""
      }
    }
  }
}
node {
  name: "zeros_like_1/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 3
  

In [203]:
s = tf.Variable(2, name='scalar')
m = tf.Variable([[0,1], [2,3]], name= 'matrix')
w = tf.Variable(tf.zeros([784, 10]))

In [204]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[0,1],[2,3]]))
w = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

In [205]:
with tf.Session() as sess:
    print('a')
    # sess.run(w)# FailedPreconditionError: Attempting to use uninitialized value Variable

# the easiest way is initializing all variables at once
#Initialize a single variable
w = tf.Variable(tf.zeros([784, 10]))
with tf.Session() as sess:
    # sess.run(tf.variables_initializer([a,b]))
    sess.run(w.initializer)


a


In [206]:
#Eval() a variable
w =  tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w)
    print(w.eval())

<tf.Variable 'Variable_2:0' shape=(700, 10) dtype=float32_ref>
[[-0.09450492 -0.9527787  -0.67781574 ... -1.8741708   0.26419103
   0.8916925 ]
 [ 1.560931    1.0636954   1.1630131  ...  0.57135826  0.5519468
  -0.47598276]
 [ 0.8322477  -0.5760841  -0.7859935  ...  0.45644158 -0.45659456
  -0.43862465]
 ...
 [ 0.15910354  0.05788578  0.5078449  ... -0.12611343 -1.7967244
   1.2191042 ]
 [-0.04191897 -1.0328873  -0.5905911  ... -1.740075    0.24627244
  -1.6489389 ]
 [ 0.8026406  -0.89924693  0.66143966 ...  0.6528829   0.39108956
   0.77997035]]


In [207]:
w = tf.Variable(10)
w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

10


In [212]:
w = tf.Variable(10)
assign_op = w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    sess.run(assign_op)
    print(w.eval())

100


In [224]:
my_var = tf.Variable(2, name="my_var")
my_var_times_two = my_var.assign(2*my_var)
with tf.Session() as sess:
    print(sess.run(my_var.initializer))
    print(sess.run(my_var_times_two))
    print(my_var.eval())
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))

None
4
4
8
16


In [226]:
my_var = tf.Variable(10)
with tf.Session() as sess:
    print(sess.run(my_var.initializer))
    print(sess.run(my_var.assign_add(10)))
    print(sess.run(my_var.assign_sub(2)))

None
20
18


In [231]:
w = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(w.initializer)
sess2.run(w.initializer)
print(sess1.run(w.assign_add(10)))
print(sess2.run(w.assign_sub(2)))
print(sess1.run(w.assign_add(100)))
print(sess2.run(w.assign_sub(50)))
sess1.close()
sess2.close()


20
8
120
-42


# your graph g have 5 ops: a, b, c, d, e
g = tf.get_default_graph()
with g.control_dependencies([a, b, c]):
	# 'd' and 'e' will only run after 'a', 'b', and 'c' have executed.
	d = ...
	e = …



 # Placeholders
 TF program often has 2 phases: 
1. Assemble a graph 

2. Use a session to execute operations in the graph.

⇒ Assemble the graph first without knowing the values needed for computation

Analogy:
Define the function f(x, y) = 2 * x + y without knowing value of x or y. 
x, y are placeholders for the actual values.



# Why placeholders?
We, or our clients, can later supply their own data when they need to execute the computation. 


In [236]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements

a = tf.placeholder(tf.float32, shape=[3])

# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5,5,5], tf.float32)
c = a + b
with tf.Session() as sess:
    # print(sess.run(c)) # InvalidArgumentError: a doesn’t an actual value
    print(sess.run(c, feed_dict={a:[1,2,3]}))

[6. 7. 8.]


shape= None means that tensor of any shape will be accepted as value for placeholder
shape = None is easy to construct graphs, but nightmarish for debugging

# What if want to feed multiple data points in?
You have to do it one at a time

with tf.Session() as sess:

    for a_value in list_of_values_for_a:
    
        print(sess.run(c, {a: a_value}))




# You can feed_dict any feedable tensor.
Placeholder is just a way to indicate that something must be fed
tf.Graph.is_feedable(tensor) 
# True if and only if tensor is feedable.


In [242]:
# Feeding values to TF ops 
a = tf.add(2, 5)
b = tf.multiply(a, 3)
with tf.Session() as sess:
    # compute the value of b given a is 15
    print(sess.run(b, feed_dict={a:15}))

45


# Extremely helpful for testing
Feed in dummy values to test parts of a large graph


# The trap of lazy loading*
What’s lazy loading?

Defer creating/initializing an object 
until it is needed



# Normal loading


In [253]:
tf.reset_default_graph()

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) 
writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)
writer.close()

# Lazy loading


In [255]:
tf.reset_default_graph()

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
            sess.run(tf.add(x,y)) # some decides to be clever to save on line of code
writer.close()

# Both give the same value of z What’s the problem?
## Normal loading

node {
  name: "Add"
  op: "Add"
  input: "x/read"
  input: "y/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}

Node “Add” added once to the graph definition



## Lazy loading

node {
  name: "Add_1"
  op: "Add"
  ...
  }
...
node {
  name: "Add_10"
  op: "Add"
  ...
}

Node “Add” added 10 times to the graph definition

Or as many times as you want to compute z




# Imagine you want to compute an op thousands, or millions of times!


Your graph gets bloated
Slow to load
Expensive to pass around


# One of the most common TF non-bug bugs I’ve seen on GitHub


Solution
1. Separate definition of ops from computing/running ops 
2. Use Python property to ensure function is also loaded once the first time it is called*

